/**
 * Created by wangyong on 2015/7/9.
 */
var baseUrl='./';
var tplData = {
    start:{
        baseUrl:baseUrl,
        list:[
            {
                src:'images/start-new.jpg',
                url:'#',
                name:'新品介绍'
            },{
                src:'images/start-game.jpg',
                url:'#/index/game',
                name:'翻牌有奖'
            },{
                src:'images/start-show.jpg',
                url:'#/index/show',
                name:'SHOW出流行美'
            },{
                src:'images/start-discount.jpg',
                url:'#/index/discount',
                name:'乐享巨惠'
            }

        ]
    },
    game:{
        title:'翻牌有奖',
        baseUrl:baseUrl,
        list:[
            {
                url:'',
                src:'images/poke-bg.png'
            },{
                url:'',
                src:'images/poke-bg.png'
            },{
                url:'',
                src:'images/poke-bg.png'
            },{
                url:'',
                src:'images/poke-bg.png'
            },{
                url:'',
                src:'images/poke-bg.png'
            },{
                url:'',
                src:'images/poke-bg.png'
            }
        ]
    },
    rule:{
        title:'活动规则',
        baseUrl:baseUrl,
        list:[
            {area:'华南',fst:40,sec:60,thd:100},
            {area:'华南',fst:40,sec:60,thd:100},
            {area:'华南',fst:40,sec:60,thd:100},
            {area:'华南',fst:40,sec:60,thd:100},
            {area:'华南',fst:40,sec:60,thd:100},
            {area:'华南',fst:40,sec:60,thd:100},
            {area:'华南',fst:40,sec:60,thd:100}
        ]
    },
    prodCate:{
        title:'产品分类',
        baseUrl:baseUrl,
        list:[
            {
                url:'#',
                src:'images/cate-1.jpg',
                name:'布艺系列'
            },{
                url:'#',
                src:'images/cate-2.jpg',
                name:'合金系列'
            },{
                url:'#',
                src:'images/cate-3.jpg',
                name:'套装系列'
            },{
                url:'#',
                src:'images/cate-4.jpg',
                name:'儿童系列'
            }
        ]
    },
    prodList:{
        title:'产品列表',
        baseUrl:baseUrl,
        list:[
            {
                url:'#',
                src:'images/cate-1.jpg',
                name:'水晶发夹',
                vote:383
            },{
                url:'#',
                src:'images/cate-1.jpg',
                name:'水晶发夹',
                vote:383
            },{
                url:'#',
                src:'images/cate-1.jpg',
                name:'水晶发夹',
                vote:383
            },{
                url:'#',
                src:'images/cate-1.jpg',
                name:'水晶发夹',
                vote:383
            }
        ]
    },
    homepage:{
        title:'个人主页'
    },
    discount:{
        title:'乐享钜惠',
        baseUrl:baseUrl,
        list:[
            {
                src:'images/dis-1.jpg',
                url:'javascript:;',
                name:'买满599元，即可获赠价值48元简约小巧夏日'
            },{
                src:'images/dis-2.jpg',
                url:'javascript:;',
                name:'买满999元，即可获赠价值128元精美化妆镜或价值138元自拍神器'
            },{
                src:'images/dis-3.jpg',
                url:'javascript:;',
                name:'买满1599元，即可获赠价值388元限量版水晶胸针'
            },{
                src:'images/dis-4.jpg',
                url:'javascript:;',
                name:'买满2199元，即可获赠价值598元流行美饰品百宝箱'
            }
        ]
    }
}