/**
 * Created by wangyong on 2015/7/9.
 */
var baseUrl='./';
var tplData = {
    start:{
        baseUrl:baseUrl,
        list:[
            {
                src:'images/start-new.jpg',
                url:'product.html',
                name:'新品介绍'
            },{
                src:'images/start-game.jpg',
                url:'#/index/game',
                name:'翻牌有奖'
            },{
                src:'images/start-show.jpg',
                url:'#/index/show',
                name:'SHOW出流行美'
            },{
                src:'images/start-discount.jpg',
                url:'#/index/discount',
                name:'乐享巨惠'
            }

        ]
    },
    game:{
        title:'翻牌有奖',
        baseUrl:baseUrl,
        prizeNum:0,
        prizeTimes:2,
        prizeRemoteNum:-1,
        turnImages:[],
        list:[
            {
                url:'javascript:;',
                src:'images/poke-bg.png'
            },{
                url:'javascript:;',
                src:'images/poke-bg.png'
            },{
                url:'javascript:;',
                src:'images/poke-bg.png'
            },{
                url:'javascript:;',
                src:'images/poke-bg.png'
            },{
                url:'javascript:;',
                src:'images/poke-bg.png'
            },{
                url:'javascript:;',
                src:'images/poke-bg.png'
            }
        ]
    },
    gamePrize:{
        prizes:[
            {
                title:'无中奖',
                baseUrl:baseUrl,
                times:2,
                list:[
                    {
                        url:'javascript:;',
                        src:'images/spoil-s-1.jpg',
                        name:'幻彩水晶发梳<br>100名'
                    },{
                        url:'javascript:;',
                        src:'images/spoil-s-2.jpg',
                        name:'美白旅行套<br>1000名'
                    },{
                        url:'javascript:;',
                        src:'images/spoil-s-3.jpg',
                        name:'定制收纳包<br>10000名'
                    }
                ]
            },{
                title:'一等奖',
                baseUrl:baseUrl,
                prizeName:'花千朵发饰',
                src:'images/spoil-1.jpg'
            },{
                title:'二等奖',
                baseUrl:baseUrl,
                prizeName:'凝脂莹透美白旅行套',
                src:'images/spoil-2.jpg'
            },{
                title:'三等奖',
                baseUrl:baseUrl,
                prizeName:'流行美定制收纳包',
                src:'images/spoil-3.jpg'
            }
        ]

    },
    gameAddress:{
        title:'填写地址'
    },
    gameAddressSuccess:{
        title:'提交成功'
    },
    rule:{
        title:'活动规则',
        baseUrl:baseUrl,
        list:[
            {area:'华南',fst:40,sec:60,thd:100},
            {area:'华北',fst:40,sec:60,thd:100},
            {area:'华东',fst:40,sec:60,thd:100},
            {area:'华中',fst:40,sec:60,thd:100},
            {area:'西北',fst:20,sec:30,thd:50},
            {area:'西南',fst:20,sec:30,thd:50},
            {area:'川渝',fst:20,sec:30,thd:50},
            {area:'南区',fst:20,sec:30,thd:50}
        ]
    },
    menu:{
        baseUrl:baseUrl,
        ticketNum:1,
        chanceNum:0
    },
    prodCate:{
        title:'产品分类',
        baseUrl:baseUrl,
        list:[
            {
                url:'#',
                src:'images/cate-1.jpg',
                name:'布艺系列'
            },{
                url:'#',
                src:'images/cate-2.jpg',
                name:'合金系列'
            },{
                url:'#',
                src:'images/cate-3.jpg',
                name:'套装系列'
            },{
                url:'#',
                src:'images/cate-4.jpg',
                name:'儿童系列'
            }
        ]
    },
    prodList:{
        title:'产品列表',
        baseUrl:baseUrl,
        list:[
            {
                url:'#',
                src:'images/cate-1.jpg',
                name:'水晶发夹',
                vote:383
            },{
                url:'#',
                src:'images/cate-1.jpg',
                name:'水晶发夹',
                vote:383
            },{
                url:'#',
                src:'images/cate-1.jpg',
                name:'水晶发夹',
                vote:383
            },{
                url:'#',
                src:'images/cate-1.jpg',
                name:'水晶发夹',
                vote:383
            }
        ]
    },
    topList:{
        title:'排行榜',
        baseUrl:baseUrl,
        isLoading:false,
        opList:['全国','华东','华中','华南','华北','西北','西南','川渝'],
        areaId:0,
        isListEnd:false,
        lastId:1,
        list:[]
    },
    homepage:{
        title:'个人主页',
        area:'华东',
        photoId:1314,
        src:'./images/photo-1.jpg',
        praise:230,
        sort:100
    },
    discount:{
        title:'乐享钜惠',
        baseUrl:baseUrl,
        list:[
            {
                src:'images/dis-1.jpg',
                url:'javascript:;',
                name:'买满599元，即可获赠价值48元简约小巧夏日'
            },{
                src:'images/dis-2.jpg',
                url:'javascript:;',
                name:'买满999元，即可获赠价值128元精美化妆镜或价值138元自拍神器'
            },{
                src:'images/dis-3.jpg',
                url:'javascript:;',
                name:'买满1599元，即可获赠价值388元限量版水晶胸针'
            },{
                src:'images/dis-4.jpg',
                url:'javascript:;',
                name:'买满2199元，即可获赠价值598元流行美饰品百宝箱'
            }
        ]
    },
    show:{
        baseUrl:baseUrl,
        list:[
            {
                src:'images/show-pai.jpg',
                url:'javascript:;',
                name:'拍照上传'
            },{
                src:'images/show-add.jpg',
                url:'javascript:;',
                name:'本地上传'
            }
        ]
    },
    preview:{
        title:'上传照片',
        baseUrl:baseUrl,
        localId:'',
        serverId:''
    },
    showAddress:{
        title:'用户联系信息',
        baseUrl:baseUrl,
        opList:['全国','华东','华中','华南','华北','西北','西南','川渝'],
        areaId:0
    }
}