/**
 * Created by wangyong on 2015/7/9.
 */
var baseUrl='./';
var tplData = {
    start:{
        baseUrl:baseUrl,
        id:0,
        list:[
            {
                name:'1&middot;吸引人的豆蔻岁月',
                link:'#/index/top-list/2'
            },{
                name:'2&middot;甜蜜的风信年华',
                link:'#/index/top-list/3'
            },{
                name:'3&middot;玫瑰成就永恒',
                link:'#/index/top-list/4'
            },{
                name:'蒙眼化妆比赛',
                link:'#/index/top-list/5'
            },{
                name:'团队得分',
                link:'#/index/top-list/15'
            }
        ]
    },
    show:{
        baseUrl:baseUrl,
        showBtn:false,
        list:[
            {
                link:'javascript:;',
                src:'images/show-pai.jpg',
                name:'拍摄照片'
            },{
                link:'javascript:;',
                src:'images/show-add.jpg',
                name:'本地上传'
            }
        ]
    },
    preview:{
        img:''
    },
    showSuccess:{
        baseUrl:baseUrl
    },
    showList:{
        baseUrl:baseUrl,
        areas:['','华东','华中','华南','华北','西北','西南','川渝'],
        list:[]
    },
    showDetail:{

    },
    sign:{
        baseUrl:baseUrl,
        areaId:1,
        areaName:''
    },
    signSuccess:{
        baseUrl:baseUrl,
        name:'丛军华',
        phone:'020-12341234',
        area:'华中',
        num:false
    },
    signError:{
        baseUrl:baseUrl,
        name:'丛军华',
        phone:'020-12341234',
        area:'华中',
        num:false
    },
    topList: {
        baseUrl: baseUrl,
        title:'最具人气模特奖',
        hasVoteNum:0,
        stepId:0,
        votes:[],
        list: [
        ]
    },
    homepage:{
        baseUrl:baseUrl,
        src:'images/photo-1.jpg',
        vote:200,
        name:'丛军华-华中'
    },
    voteError:{
        baseUrl:baseUrl
    },
    shake:{
        title:'活动未开始，请稍候...',
        leftSecond:0
    },
    shakeGame:{
        baseUrl:baseUrl
    },
    shakeSuccess:{
        baseUrl:baseUrl
    }
}